### ISSUE TITLE
Anchor fails on Windows

### ISSUE THREAD

**Issue by umair-mirza** [project-serum/anchor#1577] opened 2022-03-08 05:54 UTC
On Windows 10 x64 created a basic Solana program using 'anchor init'.

When I run 'anchor test' I get the following errors:

![anchor](https://user-images.githubusercontent.com/42217546/157175055-03d3b524-5722-4dee-8620-e70528103040.png)

Although, the file Cargo.toml exists in C:\Users\Umair\myepicproject\programs\myepicproject.

Instead of /*/ it should be /project-name/

Seems to be a bug on Windows. Please take a look.

**Comment by fanatid** [comment] 2022-03-08 08:29
Duplicate of #1351

**Closed by fanatid** 2022-03-08 08:29 UTC

**Comment by umair-mirza** [comment] 2022-03-08 10:33
It's not a duplicate of #1351 for sure

**Comment by fanatid** [comment] 2022-03-08 16:04
`KnineVspython` write about same error in comment https://github.com/project-serum/anchor/issues/1351#issuecomment-1025306902

`Failed to obtain package metadata: cargo metadata exited with an error: error: failed to load manifest for workspace member \\?\C:\Users...`
