### ISSUE TITLE
unable to use anchor on arm

### ISSUE THREAD

**Issue by marbar3778** [project-serum/anchor#95] opened 2021-02-27 10:22 UTC
## Description 

When trying to use anchor on a m1 based mac I get the below error:

```
❯ anchor     
[1]    97137 illegal hardware instruction  anchor
```

Not sure if this is because of  a dependency but its odd because rust is emulated to use x86 instructions.

**Comment by armaniferrante** [comment] 2021-02-27 10:32
The issue is suspected to be in the idl parsing at the moment, since `cargo build-bpf` succeeds but `anchor idl parse` fails.

```
anchor idl parse -f src/lib.rs
[1]    4298 illegal hardware instruction  anchor idl parse -f src/lib.rs
```

**Comment by armaniferrante** [comment] 2021-04-02 20:08
Related https://github.com/solana-labs/solana/issues/16072

**Comment by armaniferrante** [comment] 2021-04-20 18:33
Labeling as blocked. Solana toolchain binaries don't run on M1 according to the linked issue above.

**Comment by armaniferrante** [comment] 2021-04-28 18:12
Recently addressed on the solana end https://github.com/solana-labs/solana/pull/16346.

**Comment by mschneider** [comment] 2021-06-08 04:14
Most of the solana toolchain seems to be working now quite well on a m1. I managed to compile examples with anchor and deploy them to a local-test-validator using `anchor launch`. I couldn't get `anchor test` to run though.

**Comment by armaniferrante** [comment] 2021-06-08 05:37
Note that I don't own an M1 and so don't plan on directly addressing this myself--though I'm happy to closely work with and help anyone that decides to take on this issue.

**Comment by tfrizza** [comment] 2021-06-08 14:56
@mschneider Solana v1.7 fixes most (if not all) of the M1 compatibility issues in my testing. If you want to get anchor to work on M1 you can manually update the cargo dependencies to 1.7 and build it from source. So far it's been working a treat for me the last few days. Happy to help if you have any issues.

**Comment by mschneider** [comment] 2021-06-08 16:29
How did you install 1.7? From source or via solana-install?

**Comment by tfrizza** [comment] 2021-06-09 01:32
@mschneider pretty much what @armaniferrante said, just update the package dependencies in the respective Cargo.toml files and you can install the latest solana-cli using `sh -c "$(curl -sSfL https://release.solana.com/v1.7.1/install)"`

**Comment by mschneider** [comment] 2021-06-09 14:24
A few caveats: 1.7.1's solana-test-validator crashes for me on launch
```
Ledger location: test-ledger
Log: test-ledger/validator.log
⠙ Initializing...
Illegal instruction: 4
```

Here is what I did instead to bring one up:

1. Open a Rosetta2 Terminal
2. git clone solana
3. `git checkout v1.7`
4. ran `./install/install-help.sh .` but did not add to the PATH
5. launch `./bin/solana-test-validator`

**Comment by mschneider** [comment] 2021-06-09 14:28
Next I installed the anchor-cli locally:

```
cargo install --git https://github.com/project-serum/anchor --branch armani/sol anchor-cli --locked
```

I also used `yarn link` to have my mac use the same branch to try the basic-0 example. `anchor launch` did deploy the contract on my test-validator. But I still can't run the tests:

```
basic-0 max$ anchor test
BPF SDK: /Users/max/.local/share/solana/install/releases/1.7.1/solana-release/bin/sdk/bpf
Running: rustup toolchain list -v
Running: cargo +bpf build --target bpfel-unknown-unknown --release
    Finished release [optimized] target(s) in 0.18s

To deploy this program:
  $ solana program deploy /Users/max/Code/anchor/examples/tutorial/basic-0/target/deploy/basic_0.so


  basic-0
Transaction simulation failed: Attempt to load a program that does not exist 
    
Translating error Error: failed to send transaction: Transaction simulation failed: Attempt to load a program that does not exist
    at Connection.sendEncodedTransaction (/Users/max/Code/anchor/ts/node_modules/@solana/web3.js/lib/index.cjs.js:4520:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Connection.sendRawTransaction (/Users/max/Code/anchor/ts/node_modules/@solana/web3.js/lib/index.cjs.js:4481:20)
    at async Object.sendAndConfirmRawTransaction (/Users/max/Code/anchor/ts/node_modules/@solana/web3.js/lib/index.cjs.js:6263:21)
    at async Provider.send (/Users/max/Code/anchor/ts/dist/cjs/provider.js:81:22)
    at async Object.rpc [as initialize] (/Users/max/Code/anchor/ts/dist/cjs/program/namespace/rpc.js:11:31)
    at async Context.<anonymous> (/Users/max/Code/anchor/examples/tutorial/basic-0/tests/basic-0.js:13:5)
    1) Uses the workspace to invoke the initialize instruction


  0 passing (80ms)
  1 failing

  1) basic-0
       Uses the workspace to invoke the initialize instruction:
     Error: Promise rejected with no or falsy reason
      at processTicksAndRejections (internal/process/task_queues.js:95:5)


```

**Comment by mschneider** [comment] 2021-06-09 18:46
Yes it does, looks like you have issues with your home brew installation.

**Comment by tfrizza** [comment] 2021-06-09 21:57
@NorbertBodziony I had that error too, running `brew install openssl` will fix it.

**Comment by tomlinton** [comment] 2021-06-09 22:56
#368 has been working great for me on M1. Appreciate it!

**Comment by NorbertBodziony** [comment] 2021-06-10 08:15
Managed to make it work. #368 + custom solana-test-validator build from 1.7.1 solana branch

**Comment by armaniferrante** [comment] 2021-06-11 03:59
Addressed by #368. Please re-open if there are still problems.

**Closed by armaniferrante** 2021-06-11 03:59 UTC
Labels: priority:1

**Comment by facing-n** [comment] 2021-07-02 04:48
> Managed to make it work. #368 + custom solana-test-validator build from 1.7.1 solana branch

Running into this same issue.  What exactly is your custom solana-test-validator solution?

**Comment by mdhrumil** [comment] 2021-08-06 20:33
@NorbertBodziony I'm facing the same issue with Solana v1.7.9. Not sure how to use #368 for solving the issue. Can you please help?

**Comment by NorbertBodziony** [comment] 2021-08-07 20:12
> @NorbertBodziony I'm facing the same issue with Solana v1.7.9. Not sure how to use #368 for solving the issue. Can you please help?

I would stick to 1.7.1 at least it works for me.

**Comment by mdhrumil** [comment] 2021-08-08 22:59
> > @NorbertBodziony I'm facing the same issue with Solana v1.7.9. Not sure how to use #368 for solving the issue. Can you please help?
> 
> I would stick to 1.7.1 at least it works for me.

I have switched to solana v1.7.1. The installation is valid as I can run basic commands like `solana --version`. The problem is that when I run: `solana-test-validator`, I get this error: ```
dyld: Library not loaded: /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib
  Referenced from: /Users/dhrumil/.local/share/solana/install/active_release/bin/solana-test-validator
  Reason: image not found
zsh: abort      solana-test-validator

``` like you mentioned you had gotten.

**Comment by dabit3** [comment] 2021-09-05 05:34
The problem is that when I run: `solana-test-validator`,
> I get this error:
> 
> ```
> dyld: Library not loaded: /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib
>   Referenced from: /Users/dhrumil/.local/share/solana/install/active_release/bin/solana-test-validator
>   Reason: image not found
> zsh: abort      solana-test-validator
> ```
> 
> like you mentioned you had gotten.

Also getting this error, running M1 Mac in Rosetta terminal, Solana CLI version `1.7.11`

**Comment by mdhrumil** [comment] 2021-09-07 22:57
@dabit3 Nice. I ended up switching to my Linux machine and found no issues there.

**Comment by dvcrn** [comment] 2021-09-08 07:28
@dabit3 how did you build it from source on m1? I'm not having any luck here, on neither 1.7.1 nor 1.7.11

**Comment by dvcrn** [comment] 2021-09-08 07:42
Figured it out, my issue was very dumb. It's depending on `greadlink` but didn't give me any error message that it's not installed. `brew install coreutils` to get the gnu versions

To fix the SSL error, symlink it manually: 

```
ln -sfn /opt/homebrew/Cellar/openssl@1.1/1.1.1k /usr/local/opt/openssl@1.1
```

**Comment by Findiglay** [comment] 2021-09-16 15:19
Hi @dabit3 thank you for providing this solution. Can I ask if you can clarify this:

> Then go to sdk/cargo-build-bpf from the project root.

When I download and extract solana-release-x86_64-apple-darwin.tar I get the following directory:
![Screenshot 2021-09-16 at 16 14 23](https://user-images.githubusercontent.com/5831507/133638630-5543655d-0e20-476a-b90e-b2139c5be34b.png)

Can you clarify where `cargo install --path .` should be run?

**Comment by Findiglay** [comment] 2021-09-16 18:30
Was beating my head against a wall, ended up running into the same problem as @dvcrn. This comment in the cargo-install-all.sh needs to be emphasised:

```
if [[ $OSTYPE == darwin* ]]; then
  # Mac OS X's version of `readlink` does not support the -f option,
  # But `greadlink` does, which you can get with `brew install coreutils`
  readlink_cmd="greadlink"
fi
```

**Comment by sandrocan** [comment] 2021-09-26 16:29
I was able to build from source and start a local test validator, thanks to @dabit3, but I can't run the example hello world program ( https://github.com/solana-labs/example-helloworld/blob/master/README.md )

When I run: 
`npm install`

I get this error:
`
npm ERR! enoent ENOENT: no such file or directory, open '/Users/alessandro/solana/solana-1.7.12/package.json'
`
Seems that I'm missing the package.json file. Anybody had any similiar issues?

**Comment by dabit3** [comment] 2021-09-26 16:30
@sandrocan which directory are you running `npm install` from?

**Comment by sandrocan** [comment] 2021-09-26 16:36
@dabit3 '/Users/alessandro/solana/solana-1.7.12' which is where the whole project is located

**Comment by dabit3** [comment] 2021-09-26 16:38
You should be running `npm install` from the [__hello-world__](https://github.com/solana-labs/example-helloworld) folder, which has a [package.json](https://github.com/solana-labs/example-helloworld/blob/master/package.json), not the main Solana codebase.

**Comment by sandrocan** [comment] 2021-09-26 17:02
That makes sense. Sorry I've been really confused after trying to get the validator to run. Will try that now. Thanks for your quick response and help! Much appreciated!

**Comment by ScottLozano** [comment] 2022-01-06 12:27
> 


# Slight elaboration and change on instructional provided by @dabit3 (which is how I figured this out, so thank you very much for posting this): 

Build from source allows you functionality for both solana-test-validator and allows one to utilize the anchor environment to build and test. You can use cargo build and cargo test but that will not populate the target/idl with the proper artifacts needed. 

In the below instructions, `build-source` refers to the Source code (tar.gz) file you download to follow the instructions to build from source in order to install the Solana CLI tools found here: https://docs.solana.com/cli/install-solana-cli-tools#build-from-source


Go to sdk/cargo-build-bpf from the build-source project root. From there, run the following:

$ cargo install --path .

Verify the path created by opening a separate terminal and navigating to ~/.cargo/bin. List the contents of bin with:

 $ ln -l.

You will either see SDK or cargo-build-bpf. On my Mac M1 chip running Monterey, I found the path to end with the latter.

So, On an apple M1 chip the cargo-build-bpf program is installed to the path ~/.cargo/bin/cargo-build-bpf. This will allow you to run commands like $ anchor build successfully in your local project root once you create a symlink from it to the path in your Solana source code/bin/sdk folder. 

In a separate terminal navigate to ~/.cargo/bin and create a symlink to the sdk folder in the build-source project’s bin folder, like this:

$ ln -s solana-1.9.2/bin/sdk ~/.cargo/bin/cargo-build-bpf 

Replace `solana-1.9.2` with the build-source code you downloaded earlier.

**Comment by mdhrumil** [comment] 2022-05-04 11:44
Hey @ScottLozano 

Followed the same steps as you mentioned for installing it on my Macbook air m1 chip. Getting this error when I run `anchor build` 

Can you please help? :)

<img width="924" alt="Screen Shot 2022-05-04 at 5 13 42 PM" src="https://user-images.githubusercontent.com/36199749/166674780-dbb5c5e6-deaa-4ded-aa13-8d177e4bb9ef.png">

**Comment by ScottLozano** [comment] 2022-05-04 14:12
@mdhrumil 

1. Did you install this on Rosetta terminal or ARM? I installed on ARM. Will clarify in my solution above. 
2. Did you install the symlink? 
3. I installed a different version and also, I installed the anchor-cli 0.19.0 & cargo 1.57.0 (b2e52d7ca 2021-10-21)
4. Did you initialize Anchor in the project? 

If you did the first two, possibly it's that you need to link a different path in the symlink? I see yours is through Documents. Mine is installed at root user, so: /Users/scott/.cargo/bin/

I can then see ($ls -l) this symlink which I created: 

cargo-build-bpf -> solana-1.9.2/bin/sdk

and I have the solana-1.9.2 on my Desktop


Let me know if that helps.

**Comment by ScottLozano** [comment] 2022-05-04 18:27
That’s great!
