### ISSUE TITLE
ts client issue with instruction names that end with numbers

### ISSUE THREAD

**Issue by kklas** [project-serum/anchor#1750] opened 2022-04-10 14:43 UTC
If you have an instruction that ends in a number, eg. `initialize_2`:

```
use anchor_lang::prelude::*;

declare_id!("Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS");

#[program]
pub mod foo {
    use super::*;

    pub fn initialize_2(ctx: Context<Initialize>) -> Result<()> {
        Ok(())
    }
}

#[derive(Accounts)]
pub struct Initialize {}
```

in the IDL it gets encoded as `initialize2` and because of that the wrong discriminator will get derived in the ts client because when converting from camel case to pascal case it will get converted as `initialize2` instead of `initialize_2`.

When calling this instruction from ts, due to the wrong discriminator, you get the `InstructionFallbackNotFound`:
```
Error: AnchorError occurred. Error Code: InstructionFallbackNotFound. Error Number: 101. Error Message: Fallback functions are not supported.
```

If you rename the instruction in the program to `initialize2` then it works because the discriminator now gets derived correctly.

The issue is inherently due to the conversion from camel_case to pascalCase in the IDL, The reverse cannot be done correctly in all cases.

**Comment by kevinheavey** [comment] 2022-04-10 16:46
Duplicate of https://github.com/project-serum/anchor/issues/736

**Comment by armaniferrante** [comment] 2022-04-10 16:48
Confirmed dup. Cosed.

**Closed** 2022-04-10 16:48 UTC
