### ISSUE TITLE
cli: `test` command should generate several wallets and token mints

### ISSUE THREAD

**Issue by armaniferrante** [project-serum/anchor#218] opened 2021-04-21 21:19 UTC
Furthermore, all wallets should be prefunded with lamports and all the mints.

Currently, only the configured wallet is funded with lamports and no spl tokens are minted.

**Comment by WrRaThY** [comment] 2021-08-12 02:06
hey
if I wanted to pick this up - where do I start?
I've seen `anchor/ts/src/provider.ts`, but there seem to be no prefunding in general.
the `env()` provider used in tests uses `NodeWallet` which loads the local `homedir() + "/.config/solana/id.json` and that's it.

**Comment by paul-schaaf** [comment] 2022-03-12 21:54
closing this because it seems like a duplicate of #1261

**Closed by paul-schaaf** 2022-03-12 21:54 UTC
Labels: help wanted, good first issue, cli
