### ISSUE TITLE
Allow passing named account vectors in a context

### ISSUE THREAD

**Issue by mgild** [project-serum/anchor#1001] opened 2021-11-11 11:02 UTC
Example:
```
#[derive(Accounts)]
pub struct PaymentAction<'info> {
    #[account(mut)]
    pub wallets: Vec<Account<'info, TokenAccount>>,
}
```

**Comment by mgild** [comment] 2021-11-11 11:03
Also, this presents a pretty easy way to make named accounts optional (ie when the vector is empty)

**Comment by CherryMan** [comment] 2021-11-12 21:35
Related to #617.

**Comment by mgild** [comment] 2021-11-15 13:54
> Related to #617.

This issue is unrelated

**Comment by fanatid** [comment] 2021-11-15 16:22
Duplicate of https://github.com/project-serum/anchor/issues/69

**Closed by fanatid** 2021-11-15 16:22 UTC
