### ISSUE TITLE
IDL is not emitting struct type with errror `"Type not found: {"type":{"defined":"Item"}}`

### ISSUE THREAD

**Issue by CinchBlue** [project-serum/anchor#651] opened 2021-08-30 23:15 UTC
Here is an example program that should be reproducible with a directory structure according to the tutorial (with `programs/basic-1/`-like structure):

## lib.rs

```rs
use anchor_lang::prelude::*;
use crate::priority_queue::Globals;

const PRIORITY_QUEUE_MAX_SIZE: usize = 1024;

#[account(zero_copy)]
pub struct PriorityQueue {
    pub items: [Item; 1024],
    pub curr_size: usize,
}

#[account(zero_copy)]
pub struct Item {
    pub data: i64,
}

impl PriorityQueue {
    fn new() -> Self {
        PriorityQueue { items: [Item {data: 0} ; 1024], curr_size: 0, }
    }

    fn is_full(&self) -> bool {
        self.curr_size >= PRIORITY_QUEUE_MAX_SIZE
    }

    fn is_empty(&self) -> bool {
        self.curr_size <= 0
    }

    fn push_item(&mut self, value: Item) {
        let curr_size = &mut self.curr_size;
        self.items[*curr_size] = value.into();
        *curr_size += 1;
    }

    fn try_pop_item(&mut self) -> std::result::Result<Item, ErrorCode> {
        if self.is_empty() {
            return Err(ErrorCode::CannotPopEmptyQueue);
        }

        let curr_size = &mut self.curr_size;

        let last_item = std::mem::replace(&mut self.items[*curr_size-1], Item { data: 0});
        *curr_size -= 1;

        Ok(last_item)
    }
}

////////////////////////////////////////////////////////////////////////////////

#[derive(Accounts)]
pub struct New<'info> {
    #[account(signer)]
    pub authority: AccountInfo<'info>,
}

#[derive(Accounts)]
pub struct SetEvent<'info> {
    #[account(signer)]
    pub authority: AccountInfo<'info>,
}

#[derive(Accounts)]
pub struct PushItem<'info> {
    pub item: Loader<'info, Item>,
    #[account(signer)]
    pub authority: AccountInfo<'info>,
}

#[derive(Accounts)]
pub struct PopItem<'info> {
    #[account(signer)]
    pub authority: AccountInfo<'info>,
}

////////////////////////////////////////////////////////////////////////////////

// For reference: copied from https://github.com/project-serum/anchor/blob/master/examples/zero-copy/programs/zero-copy/src/lib.rs
//
// A separate type is used for the RPC interface for two main reasons.
//
// 1. AnchorSerialize and AnchorDeserialize must be derived. Anchor requires
//    *all* instructions to implement the AnchorSerialize and AnchorDeserialize
//    traits, so any types in method signatures must as well.
// 2. All types for zero copy deserialization are `#[repr(packed)]`. However,
//    the implementation of AnchorSerialize (i.e. borsh), uses references
//    to the fields it serializes. So if we were to just throw tehse derives
//    onto the other `Event` struct, we would have references to
//    `#[repr(packed)]` fields, which is unsafe. To avoid the unsafeness, we
//    just use a separate type.
#[derive(AnchorSerialize, AnchorDeserialize)]
pub struct RpcItem {
    pub data: i64,
}

impl From<RpcItem> for Item {
    fn from(value: RpcItem) -> Self {
        Item { data: value.data }
    }
}

fn auth(globals: &Globals, key: &Pubkey) -> ProgramResult {
    if &globals.authority != key {
        return Err(ErrorCode::UnauthorizedAuthority.into());
    }
    Ok(())
}

////////////////////////////////////////////////////////////////////////////////

#[error]
pub enum ErrorCode {
    #[msg("The given authority is unauthorized to perform this operation.")]
    UnauthorizedAuthority,
    #[msg("Priority queue is full.")]
    MaxCapacityLimitReached,
    #[msg("Cannot pop from an empty priority queue.")]
    CannotPopEmptyQueue,
}


////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////

#[program]
pub mod priority_queue {
    use super::*;

    #[state(zero_copy)]
    pub struct Globals {
        pub last_item: Item,
        pub authority: Pubkey,
        pub queue: PriorityQueue,
    }

    impl Globals {
        // NOTE: zero-copy state accounts use &mut self
        pub fn new(&mut self, ctx: Context<New>) -> ProgramResult {
            self.authority = *ctx.accounts.authority.key;
            Ok(())
        }

        #[access_control(auth(&self, &ctx.accounts.authority.key))]
        pub fn push_item(
            &mut self,
            ctx: Context<PushItem>,
            item: RpcItem,
        ) -> ProgramResult {
            if self.queue.is_full() {
                return Err(ErrorCode::MaxCapacityLimitReached.into());
            }
            Ok(())
        }

        #[access_control(auth(&self, &ctx.accounts.authority.key))]
        pub fn pop_item(
            &mut self,
            ctx: Context<PopItem>,
        ) -> ProgramResult {
            let item = self.queue.try_pop_item()?;

            self.last_item = item;

            Ok(())
        }
    }
}

////////////////////////////////////////////////////////////////////////////////

#[cfg(test)]
mod tests {
    use std::mem::size_of;
    use crate::{Item};

    #[test]
    fn item_should_be_size_of_data() {
        assert_eq!(size_of::<Item>(), size_of::<i64>());
    }
}
```

## Cargo.toml
```toml
[package]
name = "priority-queue"
version = "0.1.0"
description = "Zero-copy initialized priority queue for Solana with Anchor"
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]
name = "priority_queue"

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.13.2"
```

## Xargo.toml
```toml
[target.bpfel-unknown-unkown.dependencies.std]
feature = []
```

## Generated priority_queue.json

```json
{
  "version": "0.0.0",
  "name": "priority_queue",
  "instructions": [],
  "state": {
    "struct": {
      "name": "Globals",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "lastItem",
            "type": {
              "defined": "Item"
            }
          },
          {
            "name": "authority",
            "type": "publicKey"
          },
          {
            "name": "queue",
            "type": {
              "defined": "PriorityQueue"
            }
          }
        ]
      }
    },
    "methods": [
      {
        "name": "new",
        "accounts": [
          {
            "name": "authority",
            "isMut": false,
            "isSigner": true
          }
        ],
        "args": []
      },
      {
        "name": "pushItem",
        "accounts": [
          {
            "name": "item",
            "isMut": false,
            "isSigner": false
          },
          {
            "name": "authority",
            "isMut": false,
            "isSigner": true
          }
        ],
        "args": [
          {
            "name": "item",
            "type": {
              "defined": "RpcItem"
            }
          }
        ]
      },
      {
        "name": "popItem",
        "accounts": [
          {
            "name": "authority",
            "isMut": false,
            "isSigner": true
          }
        ],
        "args": []
      }
    ]
  },
  "accounts": [
    {
      "name": "PriorityQueue",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "items",
            "type": {
              "array": [
                {
                  "defined": "Item"
                },
                1024
              ]
            }
          },
          {
            "name": "currSize",
            "type": {
              "defined": "usize"
            }
          }
        ]
      }
    },
    {
      "name": "Item",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "data",
            "type": "i64"
          }
        ]
      }
    }
  ],
  "types": [
    {
      "name": "RpcItem",
      "type": {
        "kind": "struct",
        "fields": [
          {
            "name": "data",
            "type": "i64"
          }
        ]
      }
    }
  ],
  "errors": [
    {
      "code": 300,
      "name": "UnauthorizedAuthority",
      "msg": "The given authority is unauthorized to perform this operation."
    },
    {
      "code": 301,
      "name": "MaxCapacityLimitReached",
      "msg": "Priority queue is full."
    },
    {
      "code": 302,
      "name": "CannotPopEmptyQueue",
      "msg": "Cannot pop from an empty priority queue."
    }
  ],
  "metadata": {
    "address": "2YeGb9TEau5AZknjryWAVuEULA8tSNrMMssW823jDk68"
  }
}
```

```
     Error: Type not found: {"type":{"defined":"Item"}}
      at Function.fieldLayout (/home/atasato/node_modules/@project-serum/anchor/dist/cjs/coder/idl.js:101:31)
      at Function.fieldLayout (/home/atasato/node_modules/@project-serum/anchor/dist/cjs/coder/idl.js:111:48)
      at /home/atasato/node_modules/@project-serum/anchor/dist/cjs/coder/idl.js:126:36
      at Array.map (<anonymous>)
      at Function.typeDefLayout (/home/atasato/node_modules/@project-serum/anchor/dist/cjs/coder/idl.js:125:54)
      at /home/atasato/node_modules/@project-serum/anchor/dist/cjs/coder/accounts.js:20:46
      at Array.map (<anonymous>)
      at new AccountsCoder (/home/atasato/node_modules/@project-serum/anchor/dist/cjs/coder/accounts.js:19:38)
      at new Coder (/home/atasato/node_modules/@project-serum/anchor/dist/cjs/coder/index.js:32:25)
      at new Program (/home/atasato/node_modules/@project-serum/anchor/dist/cjs/program/index.js:54:23)
      at /home/atasato/node_modules/@project-serum/anchor/dist/cjs/workspace.js:71:44
      at Array.forEach (<anonymous>)
      at Object.get (/home/atasato/node_modules/@project-serum/anchor/dist/cjs/workspace.js:64:39)
      at Context.<anonymous> (tests/basic.js:10:42)
      at processImmediate (node:internal/timers:464:21)
```

It appears that the struct type `Item` is not being emitted into the IDL under the `types` section which is why it cannot resolve it when trying to run ANY of my tests under my `tests/` folder? This seems to interfere with the generation of the client at runtime regardless of what test is being run.

**Comment by CinchBlue** [comment] 2021-08-30 23:21
```bash
$ solana --version
solana-cli 1.7.8 (src:7aced9e7; feat:2045430982)
```

```bash
$ anchor --version
anchor-cli 0.13.2
```

**Comment by armaniferrante** [comment] 2021-08-31 00:27
The problem is that `Item` is being marked as an `account` but it is being used as a type. Try changing it to 

```
#[zero_copy]
pub struct Item {
    pub data: i64,
}
```

**Comment by kfartusov** [comment] 2021-12-13 22:59
@armaniferrante  met the same issue,  changing #[account]  on #[zero_copy] bring new issue during build step:
#[account]
    | ^^^^^^^^^^ the trait `BorshSerialize` is not implemented for `Implant`

**Comment by fanatid** [comment] 2021-12-14 06:13
Do you have `Implant` type in the code? If so you need implement `BorshSerialize` for it.

**Comment by ethergru** [comment] 2021-12-14 12:57
![image](https://user-images.githubusercontent.com/39896572/146002513-9d11fa1e-a5bf-4ab6-8482-374500085627.png)
![image](https://user-images.githubusercontent.com/39896572/146002568-5e91bec4-c301-4cf8-a2a7-b3911fc29868.png)

There is a same issue.

**Comment by fanatid** [comment] 2021-12-14 20:19
`AnchorSerialize` is not `BorshSerialize`

**Comment by kfartusov** [comment] 2021-12-15 23:16
@fanatid yes I have, but I actually do not understand what do you mean. Would you able to show an example?

**Comment by arunavo4** [comment] 2022-01-26 16:43
Anyone having same issue, you can solve it using 
```
#[derive(AnchorSerialize, AnchorDeserialize, Clone)]
pub struct HouseOwner {
    pub address: Pubkey,
    pub share: u8, // 0 - 100
}
```
The issue is sometimes by mistake you declare all struct as `#[account]` = replace => `#[derive(AnchorSerialize, AnchorDeserialize, Clone)]`

**Comment by fanatid** [comment] 2022-01-27 08:30
I'll close since no response from an issue creator.

**Closed by fanatid** 2022-01-27 08:30 UTC
