### ISSUE TITLE
`anchor build` fails when generating the IDL for a project that otherwise builds

### ISSUE THREAD

**Issue by WrRaThY** [project-serum/anchor#684] opened 2021-09-05 04:09 UTC
it fails when I try to use constants in array definitions
the error is very vague
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', lang/syn/src/idl/mod.rs:167:34
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/a178d0322ce20e33eac124758e837cbd80a6f633/library/core/src/result.rs:1355:5
   3: <anchor_syn::idl::IdlType as core::str::traits::FromStr>::from_str
   4: <core::iter::adapters::ResultShunt<I,E> as core::iter::traits::iterator::Iterator>::next
   5: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
   6: <core::iter::adapters::ResultShunt<I,E> as core::iter::traits::iterator::Iterator>::next
   7: anchor_syn::idl::file::parse_ty_defs
   8: anchor_syn::idl::file::parse
   9: anchor_cli::build_cwd
  10: anchor_cli::build_all
  11: anchor_cli::build
  12: anchor_cli::entry
  13: anchor::main
```

`constants.rs`
```
pub const ID_LENGTH: usize = 10;
```
`payment.rs`
```
use crate::constants::{ID_LENGTH};
(...)
#[derive(Accounts)]
#[instruction(_id: String, _payment_bump: u8)]
pub struct Payment<'info> {
(...)
    #[account(
    init,
    seeds = [PURCHASE_CONFIRMATION_SEED.as_bytes(), _id.as_bytes()],
    bump = _payment_bump,
    payer = user,
    )]
    pub purchase_confirmation: ProgramAccount<'info, PurchaseConfirmation>,
}
(...)
#[account]
#[derive(PartialEq, Default, Debug)]
pub struct PurchaseConfirmation {
(...)
    pub id: [u8; ID_LENGTH], 
}
```

if I change `pub id: [u8; ID_LENGTH]`, to `pub id: [u8; 10],` it works fine
changing `ID_LENGTH` to u16 and then using it like so `pub id: [u8; ID_LENGTH as usize]` also does NOT work

this could be fixed or at least the error could be more informative

**Comment by armaniferrante** [comment] 2021-09-05 04:48
Duplicate of https://github.com/project-serum/anchor/issues/335. Closing.

**Closed by armaniferrante** 2021-09-05 04:48 UTC
