### ISSUE TITLE
Support rust newtype idiom in IDL (tuple struct)

### ISSUE THREAD

**Issue by SailorSnoW** [project-serum/anchor#1719] opened 2022-04-02 00:06 UTC
IDL actually doesn't seems to generate type that use the [newtype idiom](https://doc.rust-lang.org/rust-by-example/generics/new_types.html) like:

```rust
#[derive(AnchorSerialize, AnchorDeserialize, Clone)]
pub struct Username(String);
```

but generate correctly if I change it to:
```rust
#[derive(AnchorSerialize, AnchorDeserialize, Clone)]
pub struct Username {
    s: String;
}
```

**Comment by paul-schaaf** [comment] 2022-04-04 21:51
duplicate of https://github.com/project-serum/anchor/issues/232

**Closed by paul-schaaf** 2022-04-04 21:51 UTC
